export const apiConfig = {
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL,
  signup: "signup",
  login: "login",
  forgotPassword: "forgotPassword",
  resetPassword: "resetPassword",
  addProduct: "addProduct",
  getProduct: "getProduct",
  updateProduct: "updateProduct",
  deleteProduct: "deleteProduct",
  addCategory: "addCategory",
  getCategory: "getCategory",
  updateCategory: "updateCategory",
  deleteCategory: "deleteCategory",
  allUsers: "allUsers",
  updateRole: "updateRole",
  adminResetPassword: "adminResetPassword",
  scanProduct: "scan",
  checkout: "checkout",
  getReports: "analytics",
};
